### ISSUE TITLE
🗒️ Todo

### ISSUE THREAD

**Issue by znatty22** [znatty22/keycloak-fhir-sandbox#2]
- [x] Add postgres to Smile CDR
    - Use different properties file and docker-compose
- [x] Create deployment Dockerfile for Smile CDR
- [ ] How do you turn on total counts in API
- [x] Write up demo doc or add to README
    - Describe data (2 studies, patients per study)
    - Describe clients (2 clients - one with specific study access, one with study all access)
    - Describe architecture (keycloak, smilecdr, postman, webapp to get token)
    - Arch diagram to show client credentials flow
    - GET /Patients by each client and expected results
    - GET /Patients?_tag=urn:study_id:SD-0 by each client and expected results
- [ ] Write script to register clients and roles via the Keycloak Admin API (very important for production)
    - This is important to figure out because our consent grants are based on studies. So every time a new study gets added we will need to create 3 new Keycloak roles for the consent grants: `fhir-consent-read-study|<id>`, `fhir-consent-write-study|<id>`, `fhir-consent-delete-study|<id>`. 
    - It would be annoying to have to manually create these through the UI and then manually assign these to all users that need access to these studies
- [x] Write `onAuthenticateSuccess` to extract fhir permissions from access token
- [x] Write simple consent script to extract permission from user session
- [x] Integrate this work with the real consent scripts from smile-cdr-sandbox git repo
- [ ] ~Setup OIDC auth for FHIR web app~ - smilecdr docs are annoying, and the fhir web app doesn't even work well
- [ ] Write simple FHIR web app with keycloak login to test OAuth2 app flows
- [x] Test with kf-strides Keycloak in QA environment
- [ ] Need a process for IG / data model migration
- [ ] (Maybe) Deploy this stack on fly.io
    - https://community.fly.io/t/run-keycloak-with-fly/5454/5
